### ISSUE TITLE
lxc stop does not work

### ISSUE THREAD

**Issue by niklastojts** [mikma/lxd-openwrt#1]
Thanks for getting openwrt work with LXD. Very nice!

`lxc stop <container>` does not work.
I do not know why. Apparently openwrt wants SIGUSR1 or SIGUSR2 to poweroff. I do not know what LXD sends but LXC sends SIGPWR which openwrt does not understand.
https://git.openwrt.org/?p=project/procd.git;a=blob_plain;f=signal.c;hb=HEAD
https://linuxcontainers.org/lxc/manpages/man1/lxc-stop.1.html
https://clockworkbird9.wordpress.com/2016/09/29/openwrtlede-system-boot-sequence/
http://man7.org/linux/man-pages/man5/lxc.container.conf.5.html

Here is part of `lxc config edit <container>`
```
raw.lxc: |-
  lxc.signal.halt=SIGUSR2
  lxc.signal.reboot=SIGTERM
  lxc.init.cmd=/sbin/init
```
But it does not make a difference. Any ideas?
`lxc exec <container> kill -SIGUSR2 1` works.

**Comment by niklastojts** [comment]
I did a test by patching signal.c in procd but `lxc stop <container>` still does not work.
So probably the halt signal is not sent to procd (PID 1).
```
root@me:[~/lxd-openwrt]: cat patches/procd-lede-17.01/002.lxd_signal.halt.patch 
diff --git a/signal.c b/signal.c
--- a/signal.c
+++ b/signal.c
@@ -42,6 +42,7 @@
 		event = RB_AUTOBOOT;
 		msg = "reboot";
 		break;
+	case SIGPWR:
 	case SIGUSR1:
 	case SIGUSR2:
 		event = RB_POWER_OFF;
root@me:[~/lxd-openwrt]: ./build.sh
```

**Comment by mikma** [comment]
Thanks for the report. I have committed an improved patch that works for me.

**Comment by niklastojts** [comment]
aha, needed to patch init.c also. of course!
Works for me also the patch, awesome!

**Comment by niklastojts** [comment]
I would suggest to submit this patch upstream. 
git clone https://git.openwrt.org/project/procd.git and make changes and routines described at https://openwrt.org/submitting-patches. Then in the end use git send-email too openwrt-devel@lists.openwrt.org.
