### ISSUE TITLE
ip: RTNETLINK answers: Operation not permitted in Docker

### ISSUE THREAD

**Issue by aparcar** [mikma/lxd-openwrt#13]
LXC containers work fine, but Docker contains print

    ip: RTNETLINK answers: Operation not permitted

which is executed in the preinit scripts (/lib/preinit/10_indicate_preinit). The command `ip -4 address flush dev $pi_ifname` actually causes 100% CPU usage.

You got a fix for that?

**Comment by mikma** [comment]
Using `--cap-add net_admin` in the run command should solve that. But I think this issue can be left opened since missing cap_net_admin shouldn't cause 100% CPU. It can be handled better.

**Comment by aparcar** [comment]
Closed thanks to @mikma back porting some patch
