### ISSUE TITLE
19.07 fails to patch during ./build.sh

### ISSUE THREAD

**Issue by odtgit** [mikma/lxd-openwrt#21]
```
x-x86_64/build_dir/target-x86_64_musl/libubox-2019-12-28-cd75136b/.autoremove 2>/dev/null >/dev/null
find /vol/git/lxd-openwrt/build_dir/openwrt-sdk-19.07.0-x86-64_gcc-7.5.0_musl.Linux-x86_64/build_dir/target-x86_64_mus
l/libubox-2019-12-28-cd75136b -mindepth 1 -maxdepth 1 -not '(' -type f -and -name '.*' -and -size 0 ')' -and -not -nam
echo "ubus" >> /vol/git/lxd-openwrt/build_dir/openwrt-sdk-19.07.0-x86-64_gcc-7.5.0_musl.Linux-x86_64/staging_dir/targe
l/ubus-2019-12-27-041c9d1c -mindepth 1 -maxdepth 1 -not '(' -type f -and -name '.*' -and -size 0 ')' -and -not -name '
make[2]: Entering directory '/vol/git/lxd-openwrt/dl/procd-openwrt-19.07'
touch /vol/git/lxd-openwrt/build_dir/openwrt-sdk-19.07.0-x86-64_gcc-7.5.0_musl.Linux-x86_64/build_dir/target-x86_64_mu
sl/procd-2020-01-24-31e4b2df/.prepared_dc975911d1c1dda8cfcd8ca9e8e9320d_18f1e190c5d53547fed41a3eaa76e9e9_check
. /vol/git/lxd-openwrt/build_dir/openwrt-sdk-19.07.0-x86-64_gcc-7.5.0_musl.Linux-x86_64/include/shell.sh; xzcat /vol/g
it/lxd-openwrt/build_dir/openwrt-sdk-19.07.0-x86-64_gcc-7.5.0_musl.Linux-x86_64/dl/procd-2020-01-24-31e4b2df.tar.xz |
Applying ./patches/0001-state-support-reboot-of-containers.patch using plaintext:
patching file state.c
Hunk #1 FAILED at 172.
1 out of 1 hunk FAILED -- saving rejects to file state.c.rej
Patch failed!  Please fix ./patches/0001-state-support-reboot-of-containers.patch!
make[2]: *** [Makefile:127: /vol/git/lxd-openwrt/build_dir/openwrt-sdk-19.07.0-x86-64_gcc-7.5.0_musl.Linux-x86_64/buil
d_dir/target-x86_64_musl/procd-2020-01-24-31e4b2df/.prepared_dc975911d1c1dda8cfcd8ca9e8e9320d_18f1e190c5d53547fed41a3e
aa76e9e9] Error 1
make[2]: Leaving directory '/vol/git/lxd-openwrt/dl/procd-openwrt-19.07'
time: package/lxd-procd/compile#0.62#0.45#1.02
make[1]: *** [package/Makefile:113: package/lxd-procd/compile] Error 2
make[1]: Leaving directory '/vol/git/lxd-openwrt/build_dir/openwrt-sdk-19.07.0-x86-64_gcc-7.5.0_musl.Linux-x86_64'
make: *** [/vol/git/lxd-openwrt/build_dir/openwrt-sdk-19.07.0-x86-64_gcc-7.5.0_musl.Linux-x86_64/include/toplevel.mk:2
20: package/lxd-procd/compile] Error 2
```

**Comment by odtgit** [comment]
I just removed the patch for now, container reboots fine without it aswell.

**Comment by lewis15110** [comment]
i meet the issue too.
after  run ./build, will got error below:

>  make[1] package/lxd-procd/compile
 make[2] -C package/toolchain clean-build
 make[2] -C package/toolchain compile
 make[2] -C feeds/base/package/libs/libjson-c clean-build
 make[2] -C feeds/base/package/libs/libjson-c compile
 make[2] -C feeds/base/package/utils/lua clean-build
 make[2] -C feeds/base/package/utils/lua compile
 make[2] -C feeds/base/package/libs/libubox clean-build
 make[2] -C feeds/base/package/libs/libubox compile
 make[2] -C feeds/base/package/system/ubus clean-build
 make[2] -C feeds/base/package/system/ubus compile
 make[2] -C /home/wei/code/lxd-openwrt/dl/procd-openwrt-19.07 clean-build
 make[2] -C /home/wei/code/lxd-openwrt/dl/procd-openwrt-19.07 compile
make -r package/lxd-procd/compile: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
/home/wei/code/lxd-openwrt/build_dir/openwrt-sdk-19.07.0-x86-64_gcc-7.5.0_musl.Linux-x86_64/include/toplevel.mk:218: recipe for target 'package/lxd-procd/compile' failed
make: *** [package/lxd-procd/compile] Error 1

i found a commit([state: fix reboot causing shutdown inside LXC container openwrt-19.07](https://git.openwrt.org/?p=project/procd.git;a=commit;h=31e4b2dfdbd74f7451abf876dd5d9a674af7adfd)).  from my understand, the commit fixed reboot issue,  at the same time, changed state.c , so the patch is no longer applicableneed any more. i removed and it workd for me.

> rm patches/procd-openwrt-19.07/0001-state-support-reboot-of-containers.patch

**Comment by lewis15110** [comment]
Another related commit: [procd: update to version 2020-01-24](https://github.com/openwrt/openwrt/commit/8038846b62edff5fbe20f6c4cc8050b9fd401f80)
