### ISSUE TITLE
it seems NAT loopback not work

### ISSUE THREAD

**Issue by lewis15110** [mikma/lxd-openwrt#23]
I created 19.07.0 and 19.07.1 use the script, Neither of their "NAT loopback“ functions work， Then I install offical openwrt 19.07.1 to my PC directly(no lxd), it is works fine.
Doesn't openwrt under lxd support nat loopback?  Or is there something wrong with my configuration？
> NAT loopback allows to use the external IP inside your local network and still be able to reach the server you want.

I got a global ipv4 address using pppoe in wan. I bind this ip address into a domain name. I hope to use this domain name to access my server on both the local area network and the Internet. Now only other places can do it. Not under the same network as my server.

**Comment by mikma** [comment]
> Then I install offical openwrt 19.07.1 to my PC directly(no lxd), it is works fine.

Did you use the same OpenWrt configuration in both cases? I have noticed that NAT loopback only works for local networks on OpenWrt (including on LXD) since it doesn't insert NAT reflection rules for subnets reachable by static routes.

**Comment by lewis15110** [comment]
thank you.
yes, I use same OpenWrt configration, but for LXD, i used docker at the same host, my web is setuped in the Docker, after I uninstall Docker and setup my web in host directly, NAT loopback works. 
So the NAT loopback no problem. the problem for my case is Docker changed host's network environment.
