### ISSUE TITLE
Script does not seem to compile

### ISSUE THREAD

**Issue by lockheed** [mikma/lxd-openwrt#26]
First, I tried compiling OpenWRT 19.07.1 so I changed the version in build.sh. However, the process kept failing with:

>  (...)
> Configuring ppp-mod-pppoe.
> Install iptables-mod-checksum
> Installing iptables-mod-checksum (1.8.3-1) to root...
> Copying dl/packages/x86/64/iptables-mod-checksum_1.8.3-1_x86_64.ipk.
> Installing kmod-ipt-checksum (4.14.167-1) to root...
> Copying dl/packages/x86/64/kmod-ipt-checksum_4.14.167-1_x86_64.ipk.
> Configuring kmod-ipt-checksum.
> Configuring iptables-mod-checksum.
> Disabling sysfixtime
> Disabling sysntpd
> /tmp/build.412617/rootfs/lib/functions/procd.sh: line 54: 
> /tmp/build.412617/rootfs/var/lock/procd_sysntpd.lock: No such file or directory

Then, I switched back to original 19.07.0 of the script, and compile process got further and produced this output: 

> (...)
> Upgrading urngd
> Upgrading urngd on root from 2019-06-17-c057e177-1 to 2020-01-21-c7f7b6b6-1...
> Downloading http://downloads.openwrt.org/releases/19.07.0/packages/x86_64/base/urngd_2020-01-21-c7f7b6b6-1_x86_64.ipk
> Configuring urngd.
> Upgrading ppp-mod-pppoe
> Upgrading ppp-mod-pppoe on root from 2.4.7.git-2019-05-25-2 to 2.4.7.git-2019-05-25-3...
> Copying dl/packages/x86/64/ppp-mod-pppoe_2.4.7.git-2019-05-25-3_x86_64.ipk.
> Configuring ppp-mod-pppoe.
> Install iptables-mod-checksum
> Installing iptables-mod-checksum (1.8.3-1) to root...
> Copying dl/packages/x86/64/iptables-mod-checksum_1.8.3-1_x86_64.ipk.
> Collected errors:
>  * opkg_install_pkg: Package iptables-mod-checksum sha256sum mismatch. Either the opkg or the package index are corrupt. Try 'opkg update'.
>  * opkg_install_cmd: Cannot install package iptables-mod-checksum.

However, I can't find compiled file anywhere.

**Comment by mikma** [comment]
The second problem can be worked-around by removing `dl/packages/x86/64/iptables-mod-checksum_1.8.3-1_x86_64.ipk`. I have a fix I'll commit.

But I can't reproduce the first problem. What Linux dist are you using?

**Comment by lockheed** [comment]
I am using fully updated Arch.
