### ISSUE TITLE
Support for LXD virtual machines

### ISSUE THREAD

**Issue by stemcc** [mikma/lxd-openwrt#27]
It would be great if these images could also support LXD virtual machines.

**Comment by thpryrchn** [comment]
> It would be great if these images could also support LXD virtual machines. 

Why would you want it to run as a VM? That would take more system resources, and slower network routing. The whole reason to run it in a lxd container is bare metal speed, with the security of running in an unprivileged container.

**Comment by mikma** [comment]
I think generating VM images is currently out-of-scope. They are also different since they contain a qcow2 image instead of a root file system in a tar ball.
