### ISSUE TITLE
Unable to build 19.07 for the past week or so

### ISSUE THREAD

**Issue by stgraber** [mikma/lxd-openwrt#29]
Hello,

We're building daily openwrt images which use your tool, however around a week ago this has started breaking:
  https://jenkins.linuxcontainers.org/job/image-openwrt/architecture=amd64,release=19.07,variant=default/996/console

It looks like a package conflict between openwrt-keyring and base-files with now duplicated files.
It's quite possible that the issue is with upstream openwrt but a workaround would be nice ;)

**Comment by stgraber** [comment]
@monstermunchkin

**Comment by mikma** [comment]
Thanks for the report.

**Comment by stgraber** [comment]
Thanks for the quick fix!
