### ISSUE TITLE
Specify multiple package names to install?

### ISSUE THREAD

**Issue by eisengrau** [mikma/lxd-openwrt#30]
Hello,

I'm using your script to build an LXC container at each new OpenWrt release, and it is still flawless. Question: is it possible to specify multiple values for --packages? If I try a space separated list, it won't accept it.

**Comment by mikma** [comment]
> If I try a space separated list, it won't accept it.

A space separated list should work. But don't forget to put it within quotes or escape the spaces, for example: `--packages "pkg1 pkg2 pkg3"`.

**Comment by eisengrau** [comment]
Hi there! The quotes did the trick, thank you!
